version: '3'

services:
  ldap-server:
    build: ./ldap
    container_name: ldap-server
    environment:
      LDAP_ORGANISATION: "Example Org"
      LDAP_DOMAIN: "master-ldap.com"
      LDAP_ADMIN_PASSWORD: "adminpassword"
    ports:
      - "389:389"
      - "636:636"

  nginx-server:
    build: ./nginx
    container_name: nginx-server
    ports:
      - "8080:80"
    depends_on:
      - ldap-server
    command: ["nginx", "-g", "daemon off;"]
